
export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
export const LOADED = 'LOADED'


export const GET_USER = 'GET_USER'
export const GET_USER_OWN_GAMES = 'GET_USER_OWN_GAMES'
export const GET_USER_GAME_ACHIEVEMENTS = 'GET_USER_GAME_ACHIEVEMENTS'
export const CLEAR_ERRORS_USER_OWN_GAMES='CLEAR_ERRORS_USER_OWN_GAMES'

export const FILTER_STATE_NAME_AZ='FILTER_STATE_NAME_AZ'
export const FILTER_STATE_NAME_ZA='FILTER_STATE_NAME_ZA'
export const FILTER_STATE_GAME_PLAY_TIME_MAXMIN='FILTER_STATE_GAME_PLAY_TIME_MAXMIN'
export const FILTER_STATE_GAME_PLAY_TIME_MINMAX='FILTER_STATE_GAME_PLAY_TIME_MINMAX'